### ISSUE TITLE
Osmium tags-filter might not be restrictive enough

### ISSUE THREAD

**Issue by djr4** [railnova/osrm-train-profile#8]
Hi, there should be really clear note that default filter params to extract data from osm: `nw/railway`
is really extracting more than trains. For example this normally extract all rails (including tram lines) since this is also a rail.

I think we should be really more careful to explain and parametrize this parameter when extracting data from osm.

`nw/railway="rail"` would probably extract only rails (train) which is what we want. 

Please let me know if this was intentional or we just should be more careful.

Thanks for really nice docker build/setup.

**Comment by C4ptainCrunch** [comment]
Hi @djr4,

The filter `nw/railway` you see is only there to pre-process the planet file (or the country extracts) and remove what we are sure we do not need. This reduces the dataset approx 1000x and yields a file a few MB long for the whole Europe.

This filtered file is then fed to OSRM where we do more granular filtering (eg, removing tram lines). Thus OSRM has to process only a few MB instead of GB and goes way faster.

Also, filtering on `nw/railway="rail"` would be too restrictive as we also need things like [buffer stops](https://github.com/railnova/osrm-train-profile/blob/master/basic.lua#L38-L39) and [turn tables](https://github.com/railnova/osrm-train-profile/blob/master/basic.lua#L58-L60).

Does my explanation makes sense to you ?

> Thanks for really nice docker build/setup.

You are welcome, we are happy to give back to the open source community !

**Comment by djr4** [comment]
Yes that makes sense! Thanks for clarification. However I do have some followup questions:

For example when I was investigating real from Chur to Arosa (Switzerland) gauge is mapped in OSM as narrow_gauge = 1000
Basically I think a lot of trains in Alps have this narrow gauge, so I modified lua script to take into account narrow gauge. (I guess this is freight train adopted so it's excluded for that reason.) 

I do have another question: For example this happens after training to match things via OSRM:

<img width="728" alt="Screen Shot 2020-09-03 at 11 15 53 AM" src="https://user-images.githubusercontent.com/6351012/92096204-e6409d80-edd6-11ea-88af-b6c8da91199c.png">

Do you know why this happens? (I do don't have always perfect station coordinates as start - end coordinates and I use route service on OSRM. 

Thanks

**Comment by C4ptainCrunch** [comment]
You are starting from a track on the north of the station but your destination is only accessible directly with the south tracks so the router suggests you make some maneuvers to go on the right one.
You should have a look at issue #6, it seems to be the same as your problem. 

As your original issue is solved, i'll close the thread. Feel free to re-open this one or #6 if you need more help.
